Lesson 3 Django/wiki/encyclopedia/urls.py
from django.urls import path
from . import views

app_name = "wiki"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/", views.show, name="Show"),
    path("wiki/editor/", views.new, name="new"),    
    path("wiki/rand", views.Rand, name="random"),
    path("wiki/editor/<str:Title>", views.edit, name="edit"),
    path("wiki/<str:Title>", views.show, name="show")
]

Lesson 3 Django/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

Lesson 3 Django/wiki/encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse

from . import util

#random function
import random

def Rand(request):
    Entries = util.list_entries()
    entry = Entries[random.randrange(0, len(Entries))]
    return HttpResponseRedirect(reverse('wiki:show', args=(entry,)))

def index(request):
    Entries = util.list_entries()
    result = []

    if request.method == 'GET':
        q = str(request.GET.get('q', ''))
        if q != '':
            for entry in Entries:
                if q == entry:
                    return HttpResponseRedirect(reverse('wiki:show', args=(q,)))
                if q in entry:
                    result.append(entry)
            return render(request, "encyclopedia/index.html", {
                "entries": result
            })
    
    return render(request, "encyclopedia/index.html", {
        "entries": Entries
    })

#Markdown conversion
import markdown2

def show(request, Title = None):
    Content = util.get_entry(Title)    

    if Content == None:
        Title = "Error"
        Content = "Error 404 Page not found!"
    return render(request, "encyclopedia/show.html", {
        "Title" : Title,
        "ToShow" : markdown2.markdown(Content)
    })


#Form creation
from django import forms

class NewEntriesForm (forms.Form):
    title = forms.CharField(label="Title",max_length=50)
    text = forms.CharField(label="Text", widget=forms.Textarea)

def new(request):
    if request.method == 'POST':
        form = NewEntriesForm(request.POST)        

        if form.is_valid():
            Title = form.cleaned_data["title"]
            Content = form.cleaned_data["text"]


            Entries = util.list_entries()
            for entry in Entries:
                if Title == entry:
                    return render(request,"encyclopedia/editor.html",{
                        "title": Title,
                        "form": form,
                        "error": "Error: entry already exist!"
                    })

            util.save_entry(Title, ('# '+ Title + '\n' + Content))
            return HttpResponseRedirect(reverse("wiki:show",args=(Title,)))

    return render(request,"encyclopedia/editor.html",{
        "title": None,
        "form": NewEntriesForm()
    })

    

def edit(request, Title):
    if request.method == 'POST':
        form = NewEntriesForm(request.POST)        

        if form.is_valid():
            Title = form.cleaned_data["title"]
            Content = form.cleaned_data["text"]
            util.save_entry(Title, Content)
            return HttpResponseRedirect(reverse("wiki:show",args=(Title,)))

    Content = util.get_entry(Title)
    Form = NewEntriesForm(initial={'title':Title, 'text':Content})

    return render(request,"encyclopedia/editor.html",{
        "title": Title,
        "form": Form,
        "Edit": 1
    })

Lesson 3 Django/wiki/encyclopedia/templates/encyclopedia/editor.html
{% extends "encyclopedia/layout.html" %}


{% block title %}
Editor
{% endblock %}

{% block body %}
    {% if title == None %}
        <h1>Add New Entrie</h1>
    {% else %}
        <h1>Edit {{ title }}</h1>
    {% endif %}

    {% if error != None %}
        <h1 class="error">{{ error }}</h1>
    {% endif %}

    {% if Edit == 1 %}
        <form id="editor" action="{% url 'wiki:edit' title %}" method="post">
    {% else %}
        <form id="editor" action="{% url 'wiki:new' %}" method="post">
    {% endif %}
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Save">
    </form>

{% endblock %}

Lesson 3 Django/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}


{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    {% if entries%}
        <h1>All Pages</h1>
    {% else %}
        <h1>No result found</h1>
        <h2>If you want you can add by yourself</h2>
    {% endif %}

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'wiki:show' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

Lesson 3 Django/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form>
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:new' %}">Create New Page</a> 
                </div>
                <div>
                    <a href="{% url 'wiki:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

Lesson 3 Django/wiki/encyclopedia/templates/encyclopedia/show.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ Title }}
{% endblock %}

{% block body %}

    {{ ToShow|safe|escape }}
    
{% endblock %}

{% block nav %}
    {% if Title != "Error" %}
        <a href="{% url 'wiki:edit' Title %}">Edit Entry</a>
    {% endif %}
{% endblock %}